### PR TITLE
map init when reloading

### PR DESCRIPTION
**Pull request by jnsmelinda**

### CODE REVIEW

**Review by KJ-Labs — CHANGES_REQUESTED** [review]
Please merge other branch instead of this one, as I had applied additional comments

**Comment by KJ-Labs** [comment]
Using my branch as it has additional comments and final changes unrelated to markers.

**Comment by wilbur125** [comment]
reopening pull request

**Review by wilbur125 — APPROVED** [review]

**Review by wilbur125 — APPROVED** [review]

**Review by wilbur125 — APPROVED** [review]

**Review by wilbur125 — APPROVED** [review]

**Review by wilbur125 — APPROVED** [review]

**Comment by KJ-Labs** [comment]
Data merged already from the original 110 and 112

**Pull request closed without merging**
